Repository NCAR/wrf_hydro_nwm_public, pull requests merged in 2019-08, with the labels that each got.

#329 Subsurface Routing Bugfixes
  trunk/NDHMS/Routing/Noah_distr_routing.F
  trunk/NDHMS/Routing/Noah_distr_routing_subsurface.F
Labels: bug, physics, v2.1

#335 Add a snow pack liquid water release timescale
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmpdrv.F
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmplsm.F
  trunk/NDHMS/Land_models/NoahMP/run/MPTABLE.TBL
  trunk/NDHMS/template/WCOSS/TBLS/MPTABLE.TBL
Labels: noahmp, v2.1

#338 Groundwater option - exponential w/ area normalization
  trunk/NDHMS/Data_Rec/module_namelist.F
  trunk/NDHMS/HYDRO_drv/module_HYDRO_drv.F
  trunk/NDHMS/Routing/module_GW_baseflow.F
  trunk/NDHMS/Routing/module_HYDRO_io.F
  trunk/NDHMS/Routing/module_RT.F
  trunk/NDHMS/hydro_namelists.json
Labels: calibration, v2.1
