Repository NCAR/wrf_hydro_nwm_public, pull requests merged in 2019-09, with the labels that each got.

#347 Bugfix - spatial metadata reads
  trunk/NDHMS/Routing/module_NWM_io_dict.F
Labels: bug, v2.1

#350 Level Pool Free Board Storage
  trunk/NDHMS/Routing/Reservoirs/module_levelpool.F
  trunk/NDHMS/Routing/Reservoirs/reservoir_tests.F
Labels: calibration, v2.1

#319 Collection of Noah-MP bug fixes from WRFv4.1
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmp_glacier.F
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmp_groundwater.F
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmplsm.F
Labels: calibration, noahmp, v2.1

#321 Added nwm_doxygen file that builds nwm documentation, included call a…
  trunk/NDHMS/Routing/Overland/overland.md
  trunk/NDHMS/nwm.md
  trunk/NDHMS/nwm_doxyfile
Labels: documentation

#259 Persistence-Level Pool Hybrid Module
  .gitignore
  trunk/NDHMS/Data_Rec/module_RT_data.F
  trunk/NDHMS/Data_Rec/module_namelist.F
  trunk/NDHMS/Data_Rec/namelist.inc
  trunk/NDHMS/Data_Rec/rt_include.inc
  trunk/NDHMS/Routing/Reservoirs/.gitignore
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/Makefile
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/module_levelpool.F
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/module_levelpool_properties.F
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/module_levelpool_state.F
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/module_levelpool_tests.F
  trunk/NDHMS/Routing/Reservoirs/Makefile
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/Makefile
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_properties.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_state.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_tests.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid_Module_README.md
  trunk/NDHMS/Routing/Reservoirs/Testing_Files/2010-10-01_06:00:00.15min.usgsTimeSlice.ncdf
  trunk/NDHMS/Routing/Reservoirs/Testing_Files/hybrid_persistence_levelpool_ACF.nc
  trunk/NDHMS/Routing/Reservoirs/hydro_stop.F
  trunk/NDHMS/Routing/Reservoirs/module_levelpool_tests.F
  trunk/NDHMS/Routing/Reservoirs/module_reservoir.F
  trunk/NDHMS/Routing/Reservoirs/module_reservoir_read_timeslice_data.F
  trunk/NDHMS/Routing/Reservoirs/module_reservoir_utilities.F
  trunk/NDHMS/Routing/Reservoirs/reservoir_tests.F
  trunk/NDHMS/Routing/module_HYDRO_io.F
  trunk/NDHMS/Routing/module_RT.F
  trunk/NDHMS/Routing/module_channel_routing.F
  trunk/NDHMS/compile_offline_Noah.sh
  trunk/NDHMS/compile_offline_NoahMP.sh
  trunk/NDHMS/hydro_namelists.json
  trunk/NDHMS/template/HYDRO/hydro.namelist
  trunk/NDHMS/template/setEnvar.sh
Labels: enhancement, v2.1

#336 Add damlength var
  trunk/NDHMS/Data_Rec/rt_include.inc
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/module_levelpool.F
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/module_levelpool_properties.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid.F
  trunk/NDHMS/Routing/module_HYDRO_io.F
  trunk/NDHMS/Routing/module_RT.F
Labels: Domain Change, calibration, v2.1

#356 Groundwater option - exponential w/ area normalization - part II
  trunk/NDHMS/hydro_namelists.json
Labels: groundwater, v2.1

#322 Nwm cmake
  trunk/NDHMS/CMakeLists.txt
  trunk/NDHMS/CPL/NoahMP_cpl/CMakeLists.txt
  trunk/NDHMS/Data_Rec/CMakeLists.txt
  trunk/NDHMS/Debug_Utilities/CMakeLists.txt
  trunk/NDHMS/HYDRO_drv/CMakeLists.txt
  trunk/NDHMS/Land_models/Noah/CMakeLists.txt
  trunk/NDHMS/Land_models/Noah/Noah/CMakeLists.txt
  trunk/NDHMS/Land_models/Noah/Utility_routines/CMakeLists.txt
  trunk/NDHMS/Land_models/NoahMP/CMakeLists.txt
  trunk/NDHMS/Land_models/NoahMP/Utility_routines/CMakeLists.txt
  trunk/NDHMS/Land_models/NoahMP/phys/CMakeLists.txt
  trunk/NDHMS/MPP/CMakeLists.txt
  trunk/NDHMS/Routing/CMakeLists.txt
  trunk/NDHMS/Routing/Overland/CMakeLists.txt
  trunk/NDHMS/Routing/Reservoirs/CMakeLists.txt
  trunk/NDHMS/Routing/Reservoirs/Level_Pool/CMakeLists.txt
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/CMakeLists.txt
  trunk/NDHMS/Routing/Subsurface/CMakeLists.txt
  trunk/NDHMS/cmake-modules/FindNetCDF.cmake
  trunk/NDHMS/nudging/CMakeLists.txt
  trunk/NDHMS/utils/CMakeLists.txt
Labels: build system, enhancement

#373 Noah-MP snow density checks
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmplsm.F
Labels: noahmp, v2.1
