Repository NCAR/wrf_hydro_nwm_public, pull requests merged in 2019-07, with the labels that each got.

#327 Update Code of Conduct
  CODE_OF_CONDUCT.md
Labels: license

#325 Restore older PGI compiler compatibility
  trunk/NDHMS/MPP/mpp_land.F
Labels: bug, build system

#324 Update Makefiles to use one-step preprocess/compile
  .gitignore
  trunk/NDHMS/CPL/CLM_cpl/Makefile
  trunk/NDHMS/CPL/LIS_cpl/Makefile
  trunk/NDHMS/CPL/NoahMP_cpl/Makefile
  trunk/NDHMS/CPL/Noah_cpl/Makefile
  trunk/NDHMS/CPL/WRF_cpl/Makefile
  trunk/NDHMS/Data_Rec/Makefile
  trunk/NDHMS/Debug_Utilities/Makefile
  trunk/NDHMS/HYDRO_drv/Makefile
  trunk/NDHMS/Land_models/Noah/GRAPHICS/HORIZ/Makefile
  trunk/NDHMS/Land_models/Noah/GRAPHICS/TIME_SERIES/Makefile
  trunk/NDHMS/Land_models/Noah/HRLDAS_COLLECT_DATA/Makefile
  trunk/NDHMS/Land_models/Noah/HRLDAS_COLLECT_DATA/lib/Makefile
  trunk/NDHMS/Land_models/Noah/IO_code/Makefile
  trunk/NDHMS/Land_models/Noah/Noah/Makefile
  trunk/NDHMS/Land_models/Noah/Utility_programs/Makefile
  trunk/NDHMS/Land_models/Noah/Utility_programs/gcip_sw_to_grib/Makefile
  trunk/NDHMS/Land_models/Noah/Utility_routines/Makefile
  trunk/NDHMS/Land_models/NoahMP/HRLDAS_forcing/Makefile
  trunk/NDHMS/Land_models/NoahMP/HRLDAS_forcing/lib/Makefile
  trunk/NDHMS/Land_models/NoahMP/IO_code/Makefile
  trunk/NDHMS/Land_models/NoahMP/Utility_routines/Makefile
  trunk/NDHMS/Land_models/NoahMP/phys/Makefile
  trunk/NDHMS/MPP/Makefile
  trunk/NDHMS/Routing/Makefile
  trunk/NDHMS/Routing/Overland/Makefile
  trunk/NDHMS/Routing/Reservoirs/Makefile
  trunk/NDHMS/arc/macros.gordon
  trunk/NDHMS/arc/macros.gordon.debug
  trunk/NDHMS/arc/macros.mpp.IBM.xlf90_r
  trunk/NDHMS/arc/macros.mpp.gfort
  trunk/NDHMS/arc/macros.mpp.ifort
  trunk/NDHMS/arc/macros.mpp.ifort.luna
  trunk/NDHMS/arc/macros.mpp.ifort.omp
  trunk/NDHMS/arc/macros.mpp.ifort.summit_has
  trunk/NDHMS/arc/macros.mpp.ifort.theia
  trunk/NDHMS/arc/macros.mpp.intel.cray_xc
  trunk/NDHMS/arc/macros.mpp.linux
  trunk/NDHMS/arc/macros.mpp.mpiifort
  trunk/NDHMS/arc/macros.seq.gfort
  trunk/NDHMS/arc/macros.seq.ifort
  trunk/NDHMS/arc/macros.seq.linux
  trunk/NDHMS/arc/macros.theia.debug
  trunk/NDHMS/nudging/Makefile
  trunk/NDHMS/utils/Makefile
Labels: build system, enhancement

#315 Subsurface Refactor
  trunk/NDHMS/CPL/CLM_cpl/module_clm_HYDRO.F
  trunk/NDHMS/CPL/NUOPC_cpl/wrfhydro_nuopc_gluecode.F90
  trunk/NDHMS/Data_Rec/module_RT_data.F
  trunk/NDHMS/Data_Rec/rt_include.inc
  trunk/NDHMS/HYDRO_drv/module_HYDRO_drv.F
  trunk/NDHMS/Routing/Makefile
  trunk/NDHMS/Routing/Noah_distr_routing.F
  trunk/NDHMS/Routing/Noah_distr_routing_overland.F
  trunk/NDHMS/Routing/Noah_distr_routing_subsurface.F
  trunk/NDHMS/Routing/Overland/module_overland.F
  trunk/NDHMS/Routing/Overland/module_overland_control.F
  trunk/NDHMS/Routing/Overland/module_overland_routing_properties.F
  trunk/NDHMS/Routing/Subsurface/Makefile
  trunk/NDHMS/Routing/Subsurface/module_subsurface.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_grid_transform.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_input.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_output.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_properties.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_state.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_static_data.F
  trunk/NDHMS/Routing/Subsurface/subsurface_tests.F
  trunk/NDHMS/Routing/module_NWM_io.F
  trunk/NDHMS/Routing/module_RT.F
  trunk/NDHMS/Routing/module_gw_gw2d.F
  trunk/NDHMS/arc/Makefile.mpp
Labels: modularization, v2.1

#328 Subsurface and Disag Pretty-ing Up
  trunk/NDHMS/Routing/Noah_distr_routing.F
  trunk/NDHMS/Routing/Noah_distr_routing_overland.F
  trunk/NDHMS/Routing/Noah_distr_routing_subsurface.F
  trunk/NDHMS/Routing/Overland/module_overland_routing_properties.F
  trunk/NDHMS/Routing/Subsurface/module_subsurface_properties.F
  trunk/NDHMS/Routing/module_RT.F
Labels: code cleanup, v2.1

#320 Noah-MP pedotransfer function addition
  trunk/NDHMS/Land_models/NoahMP/IO_code/module_NoahMP_hrldas_driver.F
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmpdrv.F
  trunk/NDHMS/Land_models/NoahMP/phys/module_sf_noahmplsm.F
  trunk/NDHMS/Land_models/NoahMP/run/MPTABLE.TBL
Labels: noahmp, v2.1
