Repository NCAR/wrf_hydro_nwm_public, pull requests merged in 2019-10, with the labels that each got.

#357 Orchestrator config io
  trunk/NDHMS/CPL/CLM_cpl/module_clm_HYDRO.F
  trunk/NDHMS/CPL/LIS_cpl/module_lis_HYDRO.F
  trunk/NDHMS/CPL/NoahMP_cpl/hrldas_drv_HYDRO.F
  trunk/NDHMS/CPL/NoahMP_cpl/module_hrldas_HYDRO.F
  trunk/NDHMS/CPL/Noah_cpl/hrldas_drv_HYDRO.F
  trunk/NDHMS/CPL/Noah_cpl/module_hrldas_HYDRO.F
  trunk/NDHMS/CPL/WRF_cpl/module_wrf_HYDRO.F
  trunk/NDHMS/CPL/WRF_cpl/module_wrf_HYDRO_downscale.F
  trunk/NDHMS/HYDRO_drv/module_HYDRO_drv.F
  trunk/NDHMS/IO/Makefile
  trunk/NDHMS/IO/netcdf_layer.f90
  trunk/NDHMS/Land_models/NoahMP/IO_code/Makefile
  trunk/NDHMS/Land_models/NoahMP/IO_code/main_hrldas_driver.F
  trunk/NDHMS/Land_models/NoahMP/IO_code/module_NoahMP_hrldas_driver.F
  trunk/NDHMS/OrchestratorLayer/Makefile
  trunk/NDHMS/OrchestratorLayer/config.f90
  trunk/NDHMS/OrchestratorLayer/io_manager.f90
  trunk/NDHMS/OrchestratorLayer/orchestrator.f90
  trunk/NDHMS/Routing/Makefile
  trunk/NDHMS/Routing/Noah_distr_routing.F
  trunk/NDHMS/Routing/module_HYDRO_io.F
  trunk/NDHMS/Routing/module_HYDRO_utils.F
  trunk/NDHMS/Routing/module_NWM_io.F
  trunk/NDHMS/Routing/module_NWM_io_dict.F
  trunk/NDHMS/Routing/module_RT.F
  trunk/NDHMS/Routing/module_UDMAP.F
  trunk/NDHMS/Routing/module_channel_routing.F
  trunk/NDHMS/Routing/module_gw_gw2d.F
  trunk/NDHMS/Routing/module_reservoir_routing.F
  trunk/NDHMS/arc/Makefile.mpp
  trunk/NDHMS/nudging/module_nudging_io.F
  trunk/NDHMS/nudging/module_stream_nudging.F
Labels: v2.1

#366 Persistence mass balance update
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_properties.F
  trunk/NDHMS/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_tests.F
  trunk/NDHMS/Routing/Reservoirs/Testing_Files/2010-10-01_06:00:00.15min.usgsTimeSlice.ncdf
  trunk/NDHMS/Routing/Reservoirs/Testing_Files/hybrid_persistence_levelpool_ACF.nc
  trunk/NDHMS/Routing/Reservoirs/module_reservoir_read_timeslice_data.F
  trunk/NDHMS/Routing/Reservoirs/module_reservoir_utilities.F
  trunk/NDHMS/Routing/Reservoirs/reservoir_tests.F
  trunk/NDHMS/Routing/module_HYDRO_io.F
  trunk/NDHMS/hydro_namelists.json
Labels: v2.1-wm

#387 Fix OrchestratorLayer crash with gfortran-9.x
  trunk/NDHMS/OrchestratorLayer/io_manager.f90
Labels: bug

#348 RFC Forecasts Module - Initial Class Structure
  trunk/NDHMS/CMakeLists.txt
  trunk/NDHMS/Routing/CMakeLists.txt
  trunk/NDHMS/Routing/Reservoirs/CMakeLists.txt
  trunk/NDHMS/Routing/Reservoirs/Makefile
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts/CMakeLists.txt
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts/Makefile
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_properties.F
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_state.F
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_tests.F
  trunk/NDHMS/Routing/Reservoirs/RFC_Forecasts_Module_README.md
  trunk/NDHMS/Routing/Reservoirs/reservoir_tests.F
  trunk/NDHMS/Routing/module_RT.F
Labels: v2.1-wm
