Repository NCAR/wrf_hydro_nwm_public, pull requests merged in 2020-10, with the labels that each got.

#503 Update default parameters for gridded routing
  trunk/NDHMS/template/HYDRO/CHANPARM.TBL
Labels: v5.2

#519 Add new feature contributor checklist to contributor guidelines.
  .github/CONTRIBUTING.md
Labels: documentation

#464 Add ISLAKE to relevant NoahMP code
  trunk/NDHMS/Data_Rec/rt_include.inc
  trunk/NDHMS/HYDRO_drv/module_HYDRO_drv.F
  trunk/NDHMS/Land_models/NoahMP/HRLDAS_forcing/create_forcing.F
  trunk/NDHMS/Land_models/NoahMP/HRLDAS_forcing/lib/module_geo_em.F
  trunk/NDHMS/Land_models/NoahMP/IO_code/module_NoahMP_hrldas_driver.F
  trunk/NDHMS/Land_models/NoahMP/IO_code/module_hrldas_netcdf_io.F
  trunk/NDHMS/Routing/module_HYDRO_io.F
  trunk/NDHMS/Routing/module_lsm_forcing.F
Labels: v5.2

#522 Remove no longer relevant namelist check for reach lakes
  trunk/NDHMS/OrchestratorLayer/config.f90
Labels: bug, v5.2

#525 Deactivate MPI calls and writing of reservoir_assimilated_source_file
  trunk/NDHMS/Routing/module_NWM_io.F
  trunk/NDHMS/Routing/module_channel_routing.F
Labels: v2.1, v2.1-wm

#489 fixed namelist bugs on crop and soil
  trunk/NDHMS/OrchestratorLayer/config.f90
Labels: bug, v5.2

#524 Add -std=legacy to macros to support gnu >= 10.0.1
  trunk/NDHMS/arc/macros.mpp.gfort
Labels: build system, compiler, v5.2
